version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"  # Mapea el puerto 27017 del contenedor al host
    volumes:
      - mongo_data:/data/db  # Persistencia de datos
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Usuario root
      MONGO_INITDB_ROOT_PASSWORD: example  # Contraseña root

volumes:
  mongo_data:
